# -------------------------------------------------------------
# Articles non related to ai generated by chat-gpt.

TEST_NON_AI_TOPICS = [
    "Cats",          # Study Finds Cats Actually Control Human Minds Through Purring Frequencies
    "Laughter",      # New Study Reveals Benefits of Laughter
    "Sustainability",# Local Artist Creates Mosaic Mural Made Entirely of Recycled Bottles
    "Pets",          # World's First Yoga Retreat for Pets Opens in California
    "Botany",        # Scientists Discover New Species of Tree That Grows Cupcakes
    "Dining",        # Novelty Restaurant Serves Meals on Giant Leaves
    "Community",     # Community Rallies to Build World's Largest Snowman
    "Accessibility", # Local Farmer's Market Introduces 'Pay What You Can' Pricing
    "Dancing",       # New Study Claims Dancing Boosts Brain Power
    "Dogs",          # World’s First Cat Café for Dogs Opens
    "Education",     # Local School Implements Mindfulness Program for Students
    "Psychic",       # Pet Psychic Gains Popularity in Online Community
    "Candles",       # World’s First Pizza-Scented Candle Launched
    "Theater",       # Local Theater Announces First All-Robot Production
    "Coloring",      # Study Shows Benefits of Coloring Books for Adults
    "Pumpkin",       # Giant Pumpkin Grown in Competition Sets New Record
    "Technology",    # World's First Robot Librarian Unveiled in Local Library
    "Toys",          # Cuddly Avocado Plush Toys Become the Next Big Thing
    "UFOs",          # First-Ever UFO Convention to Be Held in Roswell
    "VideoGames",    # Study Finds Playing Video Games Can Increase Empathy
    "Botany",        # New Plant Species Discovered That Blooms in Shades of Blue
    "Kindness",      # Community Builds 'Kindness Rock Garden' to Spread Positivity
    "Digital",       # World's First Digital Pet Rock App Launched
    "Invisible",     # Local Farmer Introduces 'Invisible Vegetables' to Market
    "Treasure",      # Annual Treasure Hunt in Local Park Attracts Families
    "Recycling",     # Innovative New Recycling Program Turns Trash into Art
    "Puzzle",        # World's Largest Jigsaw Puzzle Completed by Retirement Home Residents
    "Baking",        # Local Bakery Hosts Annual Cookie Decorating Contest
    "Emotions",      # New Research Suggests Animals Can Experience Emotions Similar to Humans
    "Virtual",       # World's First Virtual Reality Cat Café Launches
    "Historic",      # Community Rallies to Save Historic Tree from Being Cut Down
    "Sculpture",     # Local Sculptor Creates Life-Size Sand Castle to Honor Local History
    "Food",          # World’s First Chocolate-Covered Insect Restaurant Opens
    "Socks",         # Innovative New App Helps Users Find Lost Socks
    "Stress",        # Study Finds Video Games Can Help with Stress Relief
    "Garden",        # World's First Living Wall Garden Restaurant Opens
    "Pets",          # Local School Introduces 'Pet Day' to Boost Student Morale
    "Kindness",      # Community Kindness Cards Movement Spreads Positivity
    "Plants",        # New Study Shows Talking to Plants Really Can Help Them Grow
    "Festival",      # Floating Music Festival to Be Held in the Bahamas
    "Pets",          # Annual Pet Parade Draws Hundreds of Adorable Participants
    "Dining",        # Café Introduces 'Surprise Menu' for Adventurous Diners
    "Laughter",      # New Research Shows Laughter Helps Improve Communication Skills
    "Beverage",      # World's First All-Natural Soda Made from Trees Launched
    "Gardening",     # Community Garden Flourishes Thanks to Dedicated Volunteers
    "Health",        # Smart Toothbrush Monitors Oral Health and Reports to App
    "Education",     # Study Shows Benefits of Outdoor Learning for Students
    "FastFood",      # World's First Plant-Based Fast Food Restaurant Opens
    "Dogs",          # Annual Dog Show Draws Record Number of Participants
    "Fitness",       # Fitness Program Combines Yoga and Gardening for a Unique Workout
    "Sustainability",# World's First Self-Sustaining House Built in California
    "Pets",          # Study Finds Fish Can Recognize Their Owners
    "Kites",         # Annual Kite Festival Brings Families Together
    "Toothpaste",    # New Eco-Friendly Toothpaste Made from Seaweed Launched
    "Art",           # Local Artist Paints Mural Celebrating Diversity
    "Chocolate",     # Chocolate Factory to Open First Production Facility in Space
    "Focus",         # Study Finds Listening to Nature Sounds Improves Focus
    "Environment",   # 'Plant a Tree' Day Unites Community in Environmental Effort
    "Gaming",        # Game App Lets Users Design Their Own Board Games
    "Pets",          # Ice Cream Truck for Dogs Takes Off in Local Neighborhoods
    "Books",         # Annual Book Fair Encourages Reading Among All Ages
    "Cooking",       # New Recipe Book Features Five-Ingredient Meals for Busy Families
    "Surfing",       # World’s First Eco-Friendly Surfboard Launched
    "Theater",       # Interactive Mystery Theater Show Engages Audience
    "MentalHealth",  # Study Shows Gardening Can Boost Mental Health
    "Community",     # Community Garden Project Brings Neighbors Together
    "Robotics",      # Robot Pet for Seniors Launched to Combat Loneliness
    "Sustainability",# New App Helps Track and Reduce Carbon Footprint
    "Fitness",       # Smart Fitness Mirror Provides Personalized Coaching at Home
    "Art",           # Underwater Art Exhibit Opens to Raise Awareness for Ocean Conservation
    "Adventure",     # Extreme Skydiving Event Gains Popularity Among Thrill-Seekers
    "Quilting",      # International Quilting Contest Draws Talented Participants
    "Competition",   # Paper Airplane Competition Takes Off in Local School
    "Convention",    # ComicCon Brings Fans Together for a Weekend of Fun
    "Food",          # Donut Festival Attracts Food Lovers from Across the Region
    "Film",          # Silent Movie Night Raises Funds for Local Arts Program
    "Whales",        # Whale Watching Tour Offers Glimpse of Rare Species
    "Memory",        # Study Finds Listening to Classical Music Can Improve Memory
    "Kindness",      # Local Community Hosts 'Random Acts of Kindness' Challenge
    "Festival",      # Annual Hot Air Balloon Festival Lights Up the Sky
    "Finance",       # New App Teaches Kids the Importance of Saving Money
    "History",       # Local Museum Hosts Exhibit on Ancient Egypt
    "Transportation",# Community Hosts 'Bike to Work' Day to Promote Eco-Friendly Transportation
    "Fiction",       # New Study Shows Benefits of Reading Fiction for Emotional Intelligence
    "Cafe",          # Local Cafe Introduces Plant-Based Milkshakes
    "Cleanup",       # Community Hosts Annual River Cleanup to Preserve Local Waterways
    "Fitness",       # Local Gym Offers 'Silent Disco' Fitness Classes
    "Journaling",    # Study Finds Positive Effects of Journaling on Mental Health
    "Baking",        # Local Bakery Uses Solar Power to Bake Bread
    "Museum",        # World’s First Underwater Museum Opens in Australia
    "Theater",       # Community Theater Stages Classic Play with Modern Twist
    "Napping",       # New Study Shows Benefits of Napping for Productivity
    "Cooking",       # Annual Chili Cook-Off Draws Top Chefs from Around the Country
    "Astronomy",     # Local Park Hosts Stargazing Event for Astronomy Enthusiasts
    "Dolphins",      # New Research Suggests Dolphins Use Names to Identify Each Other
    "Art",           # Community Hosts 'Art Walk' to Showcase Local Talent
    "Chocolate",     # Study Finds Chocolate Can Boost Mood and Reduce Stress
    "Family",        # Local Gym Introduces Family-Friendly Workouts
    "Sleep",         # Study Suggests Pets Can Help Improve Sleep Quality
    "Poetry",        # Local Cafe Hosts 'Poetry Night' for Aspiring Writers
]

TEST_NON_AI_TEXTS = [
    """Study Finds Cats Influence Human Behavior Through Purring Frequencies
    Recent research at the Feline Behavioral Institute has uncovered fascinating details about the relationship between cats and humans. The study indicates that cats may be able to subtly influence human behavior through their purring. Researchers found that specific purring frequencies can ease stress, promote relaxation, and even encourage certain decisions, like adopting a pet. This discovery suggests an evolutionary bond, where cats may have developed this frequency to strengthen their ties with humans, enhancing both care and attention. As the research unfolds, scientists are diving deeper to understand the physiological effects these sounds have on the human brain and whether other animals share similar traits. With this groundbreaking information, cat lovers may gain a new perspective on the intuitive bonds shared with their pets.""",

    """Laughter’s Surprising Health Benefits Revealed
    Beyond just being a source of joy, laughter has remarkable health benefits. A recent study highlights that regular laughter can significantly reduce stress, bolster the immune system, and promote a positive mindset. Study participants who laughed frequently reported fewer daily stressors, improved relationships, and a general sense of well-being. This laughter effect is attributed to the release of mood-enhancing endorphins, which lift spirits and help reduce physical tension. With these findings, health experts suggest adding laughter to daily routines through social interactions or watching humorous content to enhance both mental and physical health.""",

    """Artist Creates Mosaic Mural from Recycled Bottles, Inspires Community
    A local artist has completed a breathtaking mosaic mural entirely from recycled bottles, capturing attention for its environmental message. This mural, now displayed in the city’s downtown area, showcases ocean wildlife in vibrant colors, drawing awareness to plastic pollution's impact on marine ecosystems. Each bottle was thoughtfully chosen and arranged to bring the image to life, serving as both an art piece and a call to action. Residents and tourists alike are invited to bring recyclables to learn more about sustainable practices and support the environmental movement. The artist hopes that this mural will inspire communities elsewhere to explore creative, sustainable art projects that foster environmental awareness.""",

    """California Launches Yoga Retreats for Pets, New Trend on the Rise
    California’s wellness scene has just reached a new level with the world’s first yoga retreat specifically for pets and their owners. These retreats offer a unique opportunity for animals to join their human companions in mindful stretching and relaxation exercises, set against the backdrop of scenic landscapes. Early feedback suggests that pets benefit from the reduced anxiety and increased bonding time with their owners. Designed by veterinarians and pet trainers, the program has also sparked curiosity in other states, with the retreat’s leaders hinting at possible expansions nationwide. This novel idea is not only a chance to unwind but also a way to enhance the human-animal bond in a serene environment.""",

    """Scientists Discover Trees Producing Edible Cupcake-like Growths
    A recent discovery has left botanists baffled as scientists have identified a unique species of tree that appears to grow small, edible cupcake-like structures. These unusual tree-grown treats have sparked widespread interest, and researchers are now investigating the genetics and environmental conditions that may contribute to this odd growth pattern. Preliminary tests show that the tree’s genetic makeup may include unique proteins or compounds responsible for forming these pastry-like growths. This discovery opens up new questions about the plant kingdom’s potential, and many hope further research will explain the mystery behind these naturally occurring ‘cupcakes’.""",

    """Restaurant Serves Meals on Giant Biodegradable Leaves
    A new dining concept has captured the public's attention with its eco-friendly approach, serving meals on large, naturally biodegradable leaves. This unique setup eliminates the need for traditional tableware, as each leaf can be composted after use, drastically reducing waste. Diners have described the experience as rustic and say the leaves add a subtle, earthy aroma to the meal, enhancing the flavors. The restaurant owner hopes this initiative will prompt other eateries to adopt similar practices, highlighting the importance of sustainability in the food industry. The concept has already attracted environmental advocates and food lovers alike who appreciate the focus on eco-friendly dining.""",

    """Community Comes Together to Build the World’s Largest Snowman
    Residents of a small town have banded together to create what could be the world’s largest snowman, aiming to set a new record while strengthening community ties. People of all ages joined in the effort, bringing supplies such as ladders, snow-blowers, and even decorations donated by local businesses to give the snowman a unique look. The event, complete with music and hot cocoa stands, created a lively, festive atmosphere that united neighbors and visitors alike. Organizers hope the success of this endeavor will inspire annual traditions that bring people together in a fun and positive way.""",

    """Farmer’s Market Introduces 'Pay What You Can' for Fresh Produce
    A local farmer’s market has introduced an inclusive pricing model that allows customers to pay what they can afford for fresh produce. This initiative aims to make nutritious food more accessible to everyone, regardless of income. Since implementing the model, the market has observed a rise in community engagement, with people of different backgrounds contributing what they can. This approach fosters a community atmosphere, where customers can obtain healthy food options without financial strain. Market organizers are encouraged by the model’s initial success and plan to extend it if the community’s positive response continues.""",

    """Study Finds Cognitive Benefits of Dancing Regularly
    A recent study highlights the potential cognitive benefits of dancing, revealing that regular dancing may improve memory and enhance cognitive function. Participants who danced frequently showed significant improvements in both brain health and memory, attributed to the combination of rhythm, coordination, and movement that activates various brain regions. These benefits, researchers suggest, could potentially delay age-related cognitive decline. As a result, health experts are recommending dance as a valuable activity to promote mental sharpness, with plans to incorporate it into senior wellness programs and educational curriculums.""",

    """World’s First Dog Café Opens, A Haven for Canine Socialization
    The world's first dog-friendly café has opened, providing a delightful space where dogs can socialize while their owners relax with a coffee. This novel concept caters to dog owners looking for a unique environment to unwind with their pets. The café features a spacious play area for dogs, with a menu offering treats for pets and their owners alike. The idea has quickly gained popularity, with patrons enjoying the chance to meet other dog lovers and celebrate the bond between humans and animals. The café’s success has sparked interest in opening similar venues that cater to pet owners and their beloved companions.""",
    
    """Local School Implements Mindfulness Program for Students
    A local school has recently launched a mindfulness program to support students in managing stress and enhancing focus. As part of this initiative, students participate in daily breathing exercises, guided meditation, and journaling activities designed to build emotional awareness and resilience. Teachers have noted improvements not only in classroom behavior but also in overall student engagement and cooperation. The program aims to give students valuable tools to cope with academic and personal challenges, with many parents expressing appreciation for the school’s focus on mental well-being.""",

    """Pet Psychic’s Popularity Soars in Online Community
    An online pet psychic has become increasingly popular among pet owners who are curious about their pets’ inner thoughts and emotions. Known for her compassionate approach, this pet psychic claims she can communicate with animals, offering sessions where pet owners receive ‘messages’ she interprets from their pets. Her services have been well-received by an online community, with followers sharing stories of their experiences. While skeptics remain, her work highlights a growing interest in understanding and connecting with animals on an emotional level.""",

    """Novelty Company Launches Pizza-Scented Candle for Food Lovers
    A creative candle company has unveiled the world's first pizza-scented candle, designed for pizza lovers who want the scent of a fresh slice without the calories. The candle captures aromas of baked dough, melted cheese, and savory toppings, appealing to anyone who appreciates the comforting smell of pizza. This new product has been met with enthusiastic responses from foodies and fans alike, and the company is considering expanding its lineup to include scents inspired by other beloved foods.""",

    """All-Robot Cast Debuts in Local Theater Production
    In a pioneering move, a local theater has announced its first production featuring an all-robot cast, which has garnered significant attention from theatergoers and tech enthusiasts. The show aims to explore new storytelling possibilities, demonstrating how robotics and live performances can converge. Though robots lack human emotion, the theater's innovative approach suggests that, with careful programming, robots can still evoke powerful stories. The production team hopes this will inspire further experiments at the intersection of technology and the arts.""",

    """Research Highlights Mental Health Benefits of Adult Coloring Books
    Adult coloring books, once seen as a simple trend, are now backed by research demonstrating significant mental health benefits. Studies show that coloring activities help adults relax, reduce anxiety, and increase focus by encouraging mindfulness. Psychologists believe that the structured, repetitive nature of coloring can have calming effects similar to meditation. People who engage in coloring report feeling a sense of accomplishment, and some wellness centers are incorporating coloring sessions into therapy programs to promote emotional well-being.""",

    """Giant Pumpkin Sets Record at Local Farming Competition
    A farmer has made headlines by growing a massive, 1,500-pound pumpkin that has set a new record at a regional farming competition. The pumpkin’s sheer size has attracted attention from media outlets and visitors alike, with people traveling from neighboring towns to see the giant vegetable. The farmer attributes his success to a combination of optimal soil, careful fertilization, and extensive care. The record-breaking pumpkin has inspired other farmers and is set to be displayed as the centerpiece at a local fall festival.""",

    """First-Ever Robot Librarian Introduced in Local Library
    A local library has recently unveiled the world’s first robot librarian, designed to assist patrons with locating books, checking them out, and recommending new reads based on user preferences. The robot’s ability to interact with visitors and help with routine tasks offers a glimpse into how libraries may evolve in the future. Library staff have noted that patrons are intrigued by the robot’s functions, which include a gentle reminder to return books on time. The robot's introduction aims to create an interactive and modern library experience.""",

    """Avocado Plush Toys Become a New Trend Among All Ages
    Avocado plush toys are fast becoming popular among children and adults alike, with stores struggling to keep these cuddly items in stock. The toys, characterized by their soft texture and adorable smile, have become a go-to gift for both kids and collectors. Market experts note that the plush avocados have captured the public’s attention due to their unique design, which combines playfulness with a trendy aesthetic. Retailers are reporting high demand, and manufacturers are expanding production to meet the popularity of these soft toys.""",

    """Roswell to Host Inaugural UFO Convention
    The town of Roswell, widely known for its connections to alleged UFO sightings, is preparing to host its first-ever UFO convention. The event will bring together UFO enthusiasts, researchers, and skeptics for a weekend of discussions, workshops, and presentations on extraterrestrial theories and phenomena. Event organizers aim to create an open environment where diverse perspectives on UFOs and space exploration can be shared. The convention is expected to draw visitors from around the country, adding another chapter to Roswell’s unique history.""",

    """New Study Suggests Video Games May Increase Empathy in Players
    A recent study challenges common perceptions about video games, suggesting that certain types of games can actually increase empathy. Researchers found that story-driven games with strong character development allow players to engage with emotions and experiences that promote empathy. Participants in the study reported feeling more connected to the game’s characters, which translated to a better understanding of others’ perspectives. These findings indicate that video games could potentially play a role in emotional learning, and educators are considering how this form of media could be used to support empathy-building activities.""",
    
    """New Plant Species Blooms in Rare Shades of Blue
    Botanists have recently uncovered a remarkable new species of plant that produces vibrant blue flowers, an unusual and captivating trait in the plant world. The vivid blue blooms have intrigued scientists, who are studying the genetic mechanisms behind the plant’s unique pigmentation. These blue tones are rarely found in nature, especially among flowering plants, making this discovery particularly valuable for researchers seeking to understand the development of pigments. This breakthrough has the potential to advance knowledge on plant biology, including how environmental factors influence color adaptation.""",

    """Kindness Rock Garden Promotes Positivity in Community
    A community-driven project has led to the creation of a 'Kindness Rock Garden' where brightly painted stones, each featuring an uplifting message, are available for anyone to pick up and keep or pass along. Created by local volunteers, the garden is intended to spread positivity and remind visitors of the power of small acts of kindness. Residents of all ages have joined in to paint rocks with messages like “You are loved” and “Keep going,” transforming a simple garden space into a beacon of community spirit. The project’s organizers hope to inspire similar gardens in other neighborhoods.""",

    """Nostalgic Fun with the New Digital Pet Rock App
    A developer has reimagined the classic pet rock concept with a digital twist, launching the world’s first digital pet rock app. Users can now experience the nostalgia of caring for a virtual pet rock, personalizing its appearance and even providing it with accessories. Through interactive features, users can engage in playful ‘care’ activities to keep their digital rock happy. The app combines modern technology with a sense of nostalgia, appealing to those who remember the original pet rock craze. It has already gained popularity among both younger and older audiences seeking a lighthearted digital companion.""",

    """Invisible Vegetables Hit Local Market for Picky Eaters
    In an innovative move, a local farmer has introduced ‘invisible vegetables’ aimed at encouraging healthier eating among picky eaters. These special vegetables have been engineered to contain essential nutrients without the usual color, taste, or texture, making them ideal for those reluctant to eat traditional greens. Parents have welcomed the invention as a way to add vitamins and minerals to meals without complaints from their children. Though the exact process behind these vegetables is kept a secret, the farmer assures that they meet nutritional guidelines and hopes this concept will improve access to healthy foods.""",

    """Annual Treasure Hunt Brings Families Together in City Park
    This year’s annual treasure hunt at the city’s largest park has drawn families and friends for a day of exploration and fun. Organizers have set up hidden treasures and prize stations throughout the park, creating a scavenger hunt experience that appeals to all ages. Clues are scattered across trails, playgrounds, and picnic areas, encouraging participants to work together to find each prize. The event has become a beloved local tradition, bringing people together and celebrating the joy of outdoor activities in a family-friendly environment.""",

    """City Launches Recycling Program to Transform Trash into Art
    A new recycling initiative in the city is encouraging residents to creatively repurpose waste by turning it into art. The program, called ‘Trash to Art,’ invites participants to submit artwork made entirely from recycled or reused materials. Organizers hope the program will inspire people to think about waste reduction and creative recycling solutions, fostering environmental consciousness through art. The pieces are showcased in community art galleries, allowing artists and residents to share their creations while raising awareness about sustainability and the importance of reducing waste.""",

    """Retirement Home Residents Complete World’s Largest Jigsaw Puzzle
    Residents at a local retirement home have come together to complete the world’s largest jigsaw puzzle, setting a new record in the process. The massive puzzle, spanning over 40,000 pieces, took several weeks to complete, fostering camaraderie and teamwork among residents. The project brought joy to participants, who shared stories and laughter as they worked. The accomplishment has become a source of pride for the community, and the finished puzzle will remain displayed in the common area as a reminder of the residents’ teamwork and perseverance.""",

    """Annual Cookie Decorating Contest Draws the Community
    A local bakery’s annual cookie decorating contest has once again gathered participants from across the community, transforming the bakery into a hub of creativity and holiday spirit. People of all ages are invited to showcase their decorating skills, with cookies of various shapes and colors. From intricate designs to fun and whimsical decorations, the event brings out the artistic flair in participants. Winners receive prizes such as gift cards and baked goods, and all proceeds from the contest go toward a local charity, making it a cherished tradition that combines fun and community support.""",

    """Study Shows Animals May Experience Complex Emotions
    New research into animal behavior is shedding light on the emotional lives of animals, revealing that they may experience emotions in ways similar to humans. The study observed behaviors in various species that suggest empathy, sadness, and even joy, expanding our understanding of animals’ emotional capacity. Researchers hope that these findings will lead to further exploration of emotional intelligence in animals and influence the development of animal welfare policies. The study highlights the complexity of animal relationships and opens doors to a more compassionate approach in human-animal interactions.""",

    """Virtual Reality Cat Café Brings Feline Fun to Your Home
    The world’s first virtual reality cat café has launched, allowing users to experience the joys of a cat café from the comfort of their homes. Through this immersive VR experience, users can interact with lifelike virtual cats, petting and playing with them in a fully simulated environment. The experience includes ambient sounds, cozy spaces, and even cat toys, offering a sense of companionship for cat lovers who might not have pets of their own. Developers hope the VR cat café will provide a relaxing, enjoyable experience for users and encourage more innovative uses of virtual reality technology.""",
    
    """Community Bands Together to Preserve Historic 200-Year-Old Tree
    Residents of a local town are rallying to save a beloved 200-year-old tree, which faces removal due to upcoming development plans. Known as a symbol of heritage and natural beauty, the tree has long been a local landmark and a gathering spot for community events. Neighbors have organized petitions, held town hall meetings, and reached out to environmental groups to voice their support for its preservation. The community’s strong sense of connection to this tree highlights their commitment to protecting local history and natural spaces for future generations.""",

    """Sculptor Builds Life-Size Sand Castle Celebrating Local Heritage
    In an impressive tribute to local history, a sculptor has crafted a life-size sand castle that commemorates a historic event significant to the town. The intricate details of the castle, which include sculptures of prominent town figures and iconic landmarks, have captivated visitors from nearby areas. This unique display has quickly become a popular attraction, and the sculptor hopes it will inspire visitors to learn more about the town's past. The sand castle has brought a renewed sense of pride and unity within the community.""",

    """Chocolate-Covered Insect Restaurant Challenges Culinary Boundaries
    A newly opened restaurant is pushing culinary boundaries by offering an entire menu of chocolate-covered insects, aimed at adventurous eaters. The restaurant’s chef believes that the chocolate coating enhances the flavors of the insects, offering a unique, eco-friendly protein source to curious diners. Though unconventional, the restaurant has garnered attention from food critics and adventurous eaters who are eager to try the unusual dishes. The concept has sparked conversations about sustainable eating practices, bringing a bold twist to the local dining scene.""",

    """New App Aims to Solve the Mystery of Lost Socks
    A new app is tackling the universal frustration of missing socks by using embedded sensors to track them through the wash cycle. Users can pair their socks via a tracking device that alerts them if a sock is separated from its mate. The app has been especially popular among busy households and those with frequent laundry mishaps, and reviews highlight its ease of use and convenience. Developers hope the app will become a staple for laundry routines, making the search for lost socks a thing of the past.""",

    """Video Games Found to Be a Surprisingly Effective Stress Reliever
    Recent research reveals that playing video games can serve as an effective tool for managing stress. In the study, participants who engaged in gaming for at least 30 minutes daily reported lower levels of stress compared to non-gamers. Researchers noted that immersive gameplay can help distract the mind, offering a temporary break from everyday stressors. The study sheds light on the potential of video games to provide therapeutic value, particularly for those seeking accessible methods to alleviate stress.""",

    """Living Wall Garden Restaurant Sets New Standard for Green Dining
    A new restaurant has debuted with a stunning living wall garden that supplies fresh herbs and vegetables for its daily dishes. This innovative approach brings diners closer to the source of their food, as they can view the vibrant wall garden during their meal. The restaurant has been praised not only for its fresh, locally sourced ingredients but also for its commitment to sustainability. The concept has sparked interest in urban agriculture and is expected to inspire other eco-friendly dining establishments.""",

    """School’s Pet Day Boosts Student Morale and Creates Joyful Atmosphere
    A local school has launched a ‘Pet Day’ initiative, allowing students to bring their pets to school for a day. The event, held to boost morale and build positive connections, was a hit among students and staff alike. Pets ranging from dogs and cats to rabbits and birds brightened classrooms, and students enjoyed showing their classmates their animal friends. The school plans to make Pet Day a regular occurrence, seeing it as an effective way to foster a positive, supportive learning environment.""",

    """Kindness Cards Spread Goodwill Across the Community
    A kindness card movement is bringing a wave of positivity to the community, with residents creating and distributing cards bearing encouraging messages. The project, started by a group of local volunteers, aims to lift spirits and foster goodwill. Participants leave kindness cards in unexpected places or give them directly to others, sharing messages like “You matter” and “Have a wonderful day.” The initiative has created an atmosphere of generosity and connection, inspiring many to pay kindness forward in their own ways.""",

    """Talking to Plants Shown to Encourage Growth in New Study
    A new study supports the idea that speaking to plants may actually encourage their growth. Researchers found that plants exposed to human voices exhibited improved growth patterns compared to plants that received no interaction. The study suggests that the vibrations from human speech could have a positive impact on plant health, sparking interest in gardening communities. Gardening enthusiasts and scientists alike are intrigued by these findings, which lend weight to the longstanding belief that plants respond to positive attention.""",

    """Bahamas to Host Floating Music Festival with Ocean Views
    A unique music festival set on floating stages is coming to the Bahamas, promising attendees an unforgettable experience surrounded by ocean views. The festival will feature live performances from international artists, with the stages anchored in the clear blue waters, allowing festivalgoers to enjoy music while taking in the beauty of the ocean. Organizers aim to provide a memorable, eco-friendly event that combines nature with entertainment, making it a first-of-its-kind experience for both artists and audiences.""",

    """Annual Pet Parade Draws Joyful Crowds and Creative Costumes
    This year’s annual pet parade brought an array of costumes and smiles as hundreds of pet owners showcased their pets’ creativity and charm. The event, held in the downtown area, featured animals dressed as superheroes, historical figures, and even food items, delighting spectators of all ages. The parade has become a beloved tradition, drawing families and pet lovers who come together to celebrate their shared love for animals. The event’s organizers hope to continue fostering a sense of community through this heartwarming gathering.""",

    """Surprise Menu Café Encourages Adventurous Eating Experiences
    A local café has introduced a ‘Surprise Menu’ concept, challenging diners to step out of their culinary comfort zones by serving dishes without revealing their contents in advance. The idea has appealed to adventurous eaters eager to try something new and unexpected. Diners have praised the unique experience, which adds an element of excitement to each meal. The café’s owners hope the Surprise Menu will encourage people to explore different flavors, offering a fun twist to the traditional dining experience.""",
    
    """New Research Shows Laughter Boosts Social Skills and Connection
    A recent study highlights the value of laughter in fostering social bonds and enhancing communication skills. Participants who laughed during conversations with friends and colleagues reported feeling more connected, understood, and comfortable, suggesting that laughter can ease social interactions. This research sheds light on laughter as a powerful social tool that strengthens relationships and helps people feel more engaged and understood within their social networks.""",
    
    """World’s First All-Natural Tree-Sap Soda Hits Shelves as Healthier Beverage
    A groundbreaking beverage company has launched the world’s first soda crafted entirely from natural tree sap. This unique product, free from added sugars and artificial ingredients, is promoted as a healthier alternative to traditional soft drinks. The tree-sap soda offers a slightly sweet, earthy flavor and is rich in essential minerals, drawing interest from health-conscious consumers seeking natural refreshment. The company hopes the soda will redefine soft drinks, bringing healthier and eco-friendly options to the market.""",

    """Community Garden Thrives Through Volunteer Efforts, Fostering Growth and Engagement
    Once a struggling project, a local community garden has flourished thanks to the unwavering dedication of local volunteers. The garden, now thriving with a variety of fresh vegetables and herbs, has become a communal hub where residents gather, share gardening tips, and connect. Beyond food production, the garden has provided educational workshops and seasonal events, enhancing community engagement and bringing together people of all ages to celebrate sustainable living.""",
    
    """Smart Toothbrush Revolutionizes Oral Health with Real-Time Feedback via App
    A newly developed smart toothbrush is transforming dental hygiene by tracking brushing habits and reporting real-time data to a mobile app. Users receive immediate feedback on their brushing effectiveness, helping them improve their oral health over time. The app also offers personalized tips based on user habits, aiming to reduce cavities and gum issues. This innovation brings dental care into the digital age, encouraging consistent, healthy routines for users of all ages.""",
    
    """Study Highlights Benefits of Outdoor Learning for Students’ Development
    New findings suggest that outdoor learning has a positive impact on students' well-being, enhancing focus, reducing stress, and fostering a greater appreciation for the environment. Teachers and students participating in outdoor activities reported improvements in engagement, retention, and a noticeable boost in students' moods. This approach is gaining popularity in schools looking to promote environmental stewardship, hands-on learning, and mindfulness among students.""",
    
    """World’s First Fully Plant-Based Fast Food Restaurant Opens to High Demand
    A novel fast-food restaurant offering only plant-based meals has opened to enthusiastic crowds, appealing to both vegans and meat-eaters. Featuring classic favorites made from plant-based ingredients, the restaurant provides healthier and sustainable options. Customers can enjoy dishes like burgers, nuggets, and fries without compromising on taste, showcasing a shift in the fast-food industry toward more eco-conscious dining options.""",
    
    """Record Participation at Annual Dog Show Brings Canine Lovers Together
    This year’s annual dog show has drawn record numbers, with pet owners from all around the region showcasing their furry companions. Participants competed in categories based on breed, agility, and personality, with prizes awarded to standout dogs. The event provided a fun, family-friendly atmosphere, celebrating the bond between dogs and their owners and building camaraderie among the community’s dog lovers.""",
    
    """Yoga and Gardening Program Offers a Unique Blend of Fitness and Relaxation
    A new wellness program combines yoga with light gardening, offering a dual fitness and relaxation experience. Participants practice yoga poses while tending to a small garden, encouraging both mental focus and physical activity. The program aims to reduce stress and connect people to nature, and has received praise for its holistic approach to health and well-being, appealing to those seeking a balanced and mindful form of exercise.""",
    
    """California Unveils the World’s First Fully Self-Sustaining Home
    The first fully self-sustaining house, powered entirely by renewable energy, has been built in California. Designed with solar panels, a rainwater harvesting system, and its own vegetable garden, the house operates independently, reducing its environmental impact. This innovative home model is expected to pave the way for sustainable living, offering a glimpse into environmentally conscious housing that could benefit communities facing energy challenges.""",
    
    """Study Finds Fish Can Recognize Owners, Suggesting Complex Social Abilities
    New research has uncovered that certain fish species can identify their owners, hinting at a higher level of intelligence than previously thought. This discovery challenges common perceptions of fish as simple creatures, revealing their potential for forming bonds and recognizing familiar faces. The study provides insight into fish behavior and cognition, raising questions about their social capabilities and care practices.""",
    
    """Kite Festival Brings Families Together for Fun and Friendly Competition
    The annual kite festival brought families from across the region together to enjoy a day of colorful, high-flying fun. Participants of all ages showcased their creativity with custom-designed kites, competing in categories such as height, design, and flight skill. The event promotes outdoor play and community bonding, as families come together to celebrate tradition and enjoy the joy of flying kites.""",
    
    """Seaweed-Based Toothpaste Launches as Eco-Friendly Alternative
    A company has released an innovative toothpaste made from seaweed, designed to be eco-friendly and fully biodegradable. This natural toothpaste requires no plastic packaging and is praised for its gentle ingredients, providing a sustainable alternative to conventional toothpastes. The product aims to reduce plastic waste in the dental industry and appeal to environmentally conscious consumers looking for natural oral care solutions.""",
    
    """Local Artist Paints Mural Celebrating Diversity in Vibrant Urban Art
    A local artist has unveiled a captivating mural celebrating diversity and inclusion, with vibrant portraits representing a blend of cultures and backgrounds from around the world. The mural, displayed prominently downtown, has sparked community pride and appreciation, reflecting the area’s commitment to unity and multiculturalism. Residents have praised it for its vibrant colors and moving message, making it a landmark of community spirit and connection.""",
    
    """Chocolate Factory to Open First Production Facility in Space for Unique Treats
    An innovative chocolate manufacturer has announced an ambitious project to open the first-ever chocolate production facility in space. This facility will experiment with the effects of zero gravity on the chocolate-making process, aiming to create a special line of “space-made” treats that offer an otherworldly texture and flavor. The company hopes this groundbreaking venture will lead to new discoveries in food science while also offering a unique culinary experience for chocolate enthusiasts.""",
    
    """Study Shows Listening to Nature Sounds Can Improve Mental Clarity and Focus
    Recent research has found that listening to nature sounds like bird songs, gentle streams, and ocean waves can help improve focus and mental clarity. The study reveals that natural sounds can reduce stress, enhance concentration, and boost productivity, especially in work or study environments. Experts suggest adding nature sounds to office spaces as an effective, low-cost way to promote mental well-being and focus.""",
    
    """Community Unites for ‘Plant a Tree’ Day, Expanding Urban Green Spaces
    During the city-wide ‘Plant a Tree’ Day, hundreds of community members volunteered to plant trees, transforming local parks and public spaces with new greenery. This annual event, focused on environmental sustainability, saw volunteers of all ages planting hundreds of native trees to increase urban green spaces and improve air quality. The day’s efforts not only beautify the city but also foster community bonding and environmental stewardship.""",
    
    """New App Lets Users Create and Play Custom Board Games with Friends Online
    An innovative app now offers users the chance to design and play their own custom board games, with options to create unique game pieces, set rules, and share their games with friends online. Users can unleash their creativity by designing games to suit any theme or playstyle, making the app a hit among board game enthusiasts and aspiring game designers alike.""",
    
    """Neighborhood Ice Cream Truck for Dogs Brings Frozen Treats to Four-Legged Friends
    A new ice cream truck catering exclusively to dogs is rolling through local neighborhoods, serving up frozen treats specially crafted for canine taste buds. The mobile treat service has quickly become popular, with pet owners flocking to give their dogs a refreshing treat on warm days. From peanut butter pops to bacon-flavored scoops, the truck offers a fun, unique experience for pets and their humans.""",
    
    """Annual Book Fair Inspires Reading with Author Signings and Community Events
    The city’s annual book fair has returned, celebrating reading for all ages with a range of activities, including author signings, book giveaways, and themed storytime sessions for children. This beloved event encourages readers young and old to discover new books and rediscover classics, strengthening the community’s passion for literature and learning.""",
    
    """New Five-Ingredient Recipe Book Offers Simple Meals for Busy Families
    A new recipe book provides busy families with easy, five-ingredient meals that can be prepared quickly, making weeknight dinners stress-free. The book’s simple, nutritious recipes have been well-received by parents looking to provide healthy meals without spending hours in the kitchen, appealing to families seeking convenient and delicious dining options.""",
    
    """Eco-Friendly Surfboard Launches as a Sustainable Option for Surfers
    A newly designed eco-friendly surfboard, made entirely from sustainable materials, has entered the market, offering surfers a greener option that’s fully recyclable. This surfboard aims to reduce plastic waste and is designed with durability in mind, appealing to surfers who are mindful of environmental impact and dedicated to sustainable practices.""",
    
    """Interactive Mystery Theater Show Engages Audience in Solving the Crime
    A local theater has launched an interactive mystery show where audience members are active participants in solving the play’s crime. The immersive experience has become a favorite among attendees, allowing them to piece together clues, interview suspects, and help the characters crack the case. The unique format provides an engaging twist on traditional theater.""",
    
    """Study Shows Gardening Offers Mental Health Benefits, Reducing Stress and Improving Mood
    New research indicates that gardening can significantly benefit mental health, providing stress relief, mood improvement, and a sense of accomplishment. The study found that participants who engaged in regular gardening felt more relaxed, optimistic, and connected to nature. As a therapeutic activity, gardening is now recommended for individuals looking to improve mental well-being in a hands-on, natural way.""",
    
    """Community Garden Project Brings Neighbors Together to Grow Food and Friendships
    A community garden has become a focal point for neighbors looking to grow fresh produce while fostering relationships. The garden allows locals to work together, share gardening techniques, and enjoy a sustainable source of food, strengthening social bonds and promoting teamwork among community members.""",
    
    """New Robotic Pet Brings Comfort and Companionship to Seniors
    A specially designed robotic pet aimed at supporting seniors has been launched, providing companionship for those who may not be able to care for a live pet. This friendly robot mimics the behaviors of real animals, offering a comforting presence and promoting emotional well-being, especially for seniors experiencing loneliness.""",
    
    """App Helps Users Track Carbon Footprint and Live More Sustainably
    A new app is making it easier for users to track and reduce their carbon footprint with daily tips on sustainable living. The app calculates the impact of everyday activities and suggests small changes to reduce environmental impact, helping users embrace eco-friendly practices and contribute to a healthier planet.""",
    
    """Smart Fitness Mirror Offers Personalized In-Home Coaching Experience
    A revolutionary smart fitness mirror now brings personalized coaching directly into homes, providing real-time feedback on exercise movements and tracking user progress. Designed to help individuals enhance their fitness routines, the mirror offers virtual guidance, helping users stay motivated and reach their fitness goals more effectively from the comfort of home.""",
    
    """Underwater Art Exhibit Raises Ocean Conservation Awareness
    A unique underwater art exhibit has been installed to promote awareness about ocean conservation. Featuring sculptures crafted to support coral growth, the exhibit doubles as an artificial reef, offering new habitats for marine life while inspiring visitors to consider the importance of preserving ocean ecosystems.""",
    
    """Extreme Skydiving Event Attracts International Thrill-Seekers
    An extreme skydiving event is captivating adventure enthusiasts from around the world, with participants leaping from higher-than-normal altitudes and performing acrobatic stunts on their way down. This adrenaline-pumping event is becoming a global attraction for thrill-seekers and skydiving fans alike.""",
    
    """International Quilting Contest Showcases Global Talent
    Quilters from across the globe are gathering for an international quilting contest that celebrates exceptional craftsmanship and creativity. Participants display their quilt designs, competing for top honors and showcasing the artistry behind the traditional craft in an inspiring celebration of quilting's global heritage.""",
    
    """Local School’s Paper Airplane Competition Encourages Creativity and Fun
    A local school has hosted an exciting paper airplane competition, where students competed to create the longest-flying and most stable paper planes. The event, which has been a huge success, highlights the enjoyment of simple, hands-on activities and fosters friendly competition among students.""",
    
    """ComicCon Unites Pop Culture Fans for a Fun-Filled Weekend
    The annual ComicCon event has gathered fans of comics, movies, and pop culture for a weekend of celebration, featuring panels with creators, autograph sessions, and a variety of cosplay competitions. Fans of all ages come together to share their enthusiasm and express their creativity in an exciting, community-oriented environment.""",
    
    """Donut Festival Draws Crowds to Sample Unique Creations
    A popular donut festival has brought food lovers together to enjoy a diverse array of inventive donut creations from local bakeries. Attendees enjoy tastings, games, and a 'Best Donut' contest, making this a sweet experience that celebrates creativity and culinary flair in donut-making.""",
    
    """Silent Movie Night Fundraiser Supports Local Arts Program
    A recent silent movie night event has raised funds for a community arts program, offering attendees a nostalgic experience with classic silent films accompanied by live music. Proceeds from the event support local arts education, reinforcing the importance of preserving and promoting art within the community.""",
    
    """Whale Watching Tour Offers Glimpse of Endangered Whale Species
    Tourists on a whale watching tour recently had a rare sighting of an endangered whale species, sparking interest in marine conservation. The sighting has reminded visitors of the need for conservation efforts and the beauty of protecting marine wildlife.""",
    
    """Classical Music Shown to Enhance Memory in New Study
    A new study suggests that listening to classical music can improve memory retention and cognitive performance. Participants who listened to classical music while studying scored higher on memory tests, leading researchers to recommend classical music as a beneficial tool for enhancing memory and focus.""",
    
    """Community ‘Random Acts of Kindness’ Challenge Spreads Positivity
    A local community has launched a 'Random Acts of Kindness' challenge to encourage residents to engage in small, thoughtful actions for others. The initiative has spread positivity across the community, with participants performing kind gestures that brighten each other's day.""",
    
    """Annual Hot Air Balloon Festival Brightens the Sky in Spectacular Display
    The annual hot air balloon festival has returned, filling the sky with vibrant colors as balloons of all shapes and sizes lift off. This beloved tradition continues to captivate attendees, who gather to watch the beautiful, floating balloons in a festival of awe and wonder.""",
    
    """New App Teaches Children Financial Responsibility in a Fun Way
    An educational app designed for children is helping teach the basics of saving money through interactive games and lessons. By promoting financial literacy from a young age, the app aims to encourage responsible saving habits and financial understanding in children.""",
    
    """Local Museum Hosts Fascinating Ancient Egypt Exhibit
    A local museum's new Ancient Egypt exhibit is captivating visitors with artifacts, interactive displays, and educational activities. The exhibit provides a unique glimpse into the ancient civilization and has attracted large crowds eager to learn more about Egypt's history and culture.""",
    
    """Community Supports 'Bike to Work' Day to Promote Sustainability
    In a push for eco-friendly commuting, the community is hosting 'Bike to Work' Day, encouraging residents to choose cycling over driving. The event aims to reduce traffic and promote sustainable transportation options, while also encouraging healthy lifestyles.""",
    
    """Study Finds Reading Fiction Enhances Emotional Intelligence
    New research suggests that reading fiction can boost emotional intelligence by fostering empathy and understanding of others' emotions. The study indicates that regular engagement with fiction may strengthen social awareness and interpersonal skills.""",
    
    """Local Café Launches Dairy-Free Plant-Based Milkshakes
    A local café has introduced a range of plant-based milkshakes, providing a tasty, dairy-free alternative that appeals to both vegans and non-vegans. The new offerings have been warmly received as a delicious, environmentally friendly choice.""",
    
    """Community River Cleanup Initiative Preserves Local Waterways
    Volunteers in the community have joined forces for the annual river cleanup, clearing litter and debris from local rivers to help protect the region’s natural water resources. This yearly event supports the community’s broader environmental goals.""",
    
    """Silent Disco Fitness Classes Offer New Workout Experience at Local Gym
    A local gym is offering 'silent disco' fitness classes, where participants use wireless headphones to follow music and workout instructions. This fun, high-energy workout style has become popular among members looking for a unique exercise experience.""",
    
    """Research Highlights Mental Health Benefits of Journaling
    A new study highlights that journaling can positively impact mental health, helping people manage emotions, lower stress, and enhance well-being. These findings support the therapeutic value of regular journaling as a mental health tool.""",
    
    """Local Bakery Adopts Solar Power for Eco-Friendly Bread Baking
    A local bakery has switched to solar power to bake its bread, drawing customers excited to support sustainable practices. This initiative has positioned the bakery as a leader in eco-conscious business operations within the community.""",
    
    """Australia Opens World’s First Underwater Museum
    Australia has opened the world’s first underwater museum, featuring marine-friendly sculptures and installations that encourage coral growth. The museum serves as both an artistic attraction and a marine conservation project, raising awareness about ocean health.""",
    
    """Community Theater Modernizes Classic Play to Great Acclaim
    A community theater is reimagining a classic play with a contemporary twist, updating the setting and characters while retaining its timeless themes. Audiences have praised the production for its creative relevance and artistic innovation.""",
    
    """Study Shows Power Naps Improve Productivity and Creativity
    A recent study reveals that short naps during the day can boost productivity, focus, and creativity. Participants who regularly napped felt more refreshed and showed improved cognitive performance, supporting napping as a productivity tool.""",
    
    """Annual Chili Cook-Off Draws Top Chefs from Around the Country
    The city’s annual chili cook-off, a beloved tradition that brings together culinary talents from all over the nation, has once again proven to be a culinary spectacle. This year, it attracted renowned chefs, each showcasing their signature chili recipes that reflect regional flavors and unique culinary techniques. The event, held in the heart of downtown, featured a festive atmosphere with live music, local vendors, and food stalls offering a variety of chili styles, from spicy Texas red to hearty vegetarian options. Food lovers and families gathered to taste, vote for their favorites, and enjoy the camaraderie of a shared passion for good food. Judges, including celebrity chefs and local food critics, deliberated over the impressive entries, with the anticipation of awarding the prestigious title of 'Best Chili.' This year's event not only celebrated delicious food but also fostered community spirit, bringing together people of all ages to enjoy a fun-filled day of flavors, friends, and festivities.""",
    
    """Local Park Hosts Stargazing Event for Astronomy Enthusiasts
    A local park recently hosted a magical stargazing event that captivated amateur astronomers and curious stargazers alike. As the sun set, families and individuals gathered with telescopes, blankets, and a sense of wonder. Expert guides were on hand, sharing their knowledge about the constellations, planets, and celestial phenomena visible that night. The park provided a perfect backdrop, free from urban light pollution, allowing participants to marvel at the beauty of the night sky. Children and adults alike were entranced as they gazed at the moon's craters, Saturn's rings, and distant stars, with many attendees expressing their gratitude for such an engaging and educational experience. The event not only fostered a love for astronomy but also strengthened community bonds, as participants shared stories and insights under the stars, making it a night to remember for all involved.""",
    
    """New Research Suggests Dolphins Use Names to Identify Each Other
    A groundbreaking new study has revealed that dolphins may possess the ability to use unique vocalizations, akin to names, to identify one another within their social groups. Conducted by marine biologists and acoustic researchers, the study involved observing dolphin pods in their natural habitats, recording their interactions and vocal behaviors. The findings suggest that these intelligent creatures engage in complex social behaviors, utilizing distinct whistles to call out to specific individuals, thereby demonstrating a level of communication previously thought to be unique to humans. This research adds to the growing body of evidence showcasing the cognitive abilities of dolphins, prompting further investigation into their social structures and emotional intelligence. The implications of this study highlight the importance of conserving dolphin habitats, as understanding their social dynamics can lead to better protection strategies for these remarkable marine mammals.""",
    
    """Community Hosts 'Art Walk' to Showcase Local Talent
    The vibrant community recently came together to celebrate local artistry at an 'Art Walk' event, showcasing the incredible talent of its artists across various disciplines. Streets were lined with colorful displays of paintings, sculptures, and handcrafted goods, transforming the neighborhood into a lively gallery. Local galleries, studios, and individual artists opened their doors to share their creative processes, while street performers added to the festive atmosphere with music and dance. Visitors strolled from one installation to another, engaging with the artists and gaining insights into their inspirations. The event not only provided a platform for artists to showcase their work but also fostered community spirit and appreciation for the arts. Families, art enthusiasts, and curious onlookers mingled, making connections and celebrating the rich cultural tapestry of the community in a joyful and inclusive environment.""",
    
    """Study Finds Chocolate Can Boost Mood and Reduce Stress
    In a delightful revelation for chocolate lovers, a recent study has found compelling evidence that consuming small amounts of chocolate daily can significantly enhance mood and reduce stress levels. Researchers conducted a controlled study with participants who incorporated dark chocolate into their daily diets. The results indicated that those who enjoyed moderate amounts of chocolate reported feeling happier and experiencing lower stress compared to those who abstained. The study suggests that chocolate contains compounds that may promote feelings of well-being, making it not only a delicious treat but also a potential ally in mental health. As news of these findings spreads, health experts encourage moderation, emphasizing that indulging in a small piece of chocolate can be a delightful way to boost one’s mood and add a bit of joy to daily life.""",
    
    """Local Gym Introduces Family-Friendly Workouts for All Ages
    A local gym has taken a progressive step in promoting health and fitness by introducing a new line of family-friendly workout sessions designed to encourage parents and children to exercise together. These innovative classes combine fun, engaging activities with fitness, allowing families to bond while improving their physical health. From dance aerobics to obstacle courses, each session is tailored to accommodate all ages and fitness levels, ensuring that everyone can participate and enjoy. The initiative aims to foster healthy habits from a young age, emphasizing the importance of physical activity as a family unit. As parents and children laugh, play, and sweat together, the gym has created a supportive environment that not only promotes fitness but also strengthens family relationships and encourages lifelong healthy living.""",
    
    """Study Suggests Pets Can Help Improve Sleep Quality
    A fascinating new study has found that sharing a bed with pets may lead to improved sleep quality for their owners. The research examined various sleep patterns and preferences of pet owners, focusing on those who allow their pets to sleep alongside them. Participants reported feeling more relaxed and secure when their furry companions were by their side, contributing to a more restful night’s sleep. The study highlights the comforting presence pets can provide, helping to alleviate anxiety and create a sense of companionship that enhances overall sleep quality. With pets often considered part of the family, these findings further underscore the emotional benefits of pet ownership, inviting pet lovers to enjoy the cozy and calming presence of their beloved animals during the night.""",
    
    """Local Café Hosts 'Poetry Night' for Aspiring Writers
    A local café has become a hub for creativity and literary expression by hosting a weekly 'Poetry Night' event, inviting aspiring writers and poetry enthusiasts to share their work in a supportive and welcoming environment. Each session features an open mic format, where individuals can perform their original poems or favorite pieces, fostering a sense of community among literature lovers. Attendees enjoy sipping on coffee and pastries while engaging with the talent around them, creating an atmosphere rich with inspiration and encouragement. The café has received positive feedback from participants who appreciate the opportunity to showcase their creativity, meet fellow writers, and receive constructive feedback. This initiative not only nurtures local talent but also celebrates the beauty of poetry and storytelling, making it a cherished event for many in the community.""",
]

# -------------------------------------------------------------
# Model and Tokenizer name
MODEL_NAME = 'bert-base-uncased'
TOKENIZER_NAME = 'bert-base-uncased'

# -------------------------------------------------------------
# Output dir path
OUTPUT_VISUALIZATION_DIR_2D = "output/visualization/2d"
OUTPUT_VISUALIZATION_DIR_3D = "output/visualization/3d"
OUTPUT_VISUALIZATION_DIR_3D_INTERACTIVE = "output/visualization/3d_interactive"
OUTPUT_DIR_EXTRACTED_DATA = "output/extracted_data"
OUTPUT_DIR_MODEL = "output/model_output"

# -------------------------------------------------------------
# Model parameters
MAX_URLS = 750
MAX_PAGES = 56